## ⦁	Which Tennessee counties had a disproportionately high number of opioid prescriptions?

In [1]:
# Leave commented out unless you recieve and error that you do not have psycopg2 installed.

import sys
import subprocess

try:
    import psycopg2
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--user", "psycopg2-binary"])
    import psycopg2

print(psycopg2.__version__)

2.9.11 (dt dec pq3 ext lo64)

In [2]:
import pandas as pd
from sqlalchemy import create_engine, text

In [3]:
database_name = 'prescribers'   

connection_string = f"postgresql://postgres:shami123@localhost:5432/{database_name}"

In [4]:
engine = create_engine(connection_string)

In [5]:

query = """

SELECT 
    * 
FROM 
    prescriber

"""

In [6]:
with engine.connect() as connection:
    result = connection.execute(text(query))
    prescriber = pd.DataFrame(result.fetchall(), columns=result.keys())

In [7]:
prescriber.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25050 entries, 0 to 25049
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   npi                           25050 non-null  object
 1   nppes_provider_last_org_name  25049 non-null  object
 2   nppes_provider_first_name     25050 non-null  object
 3   nppes_provider_mi             19245 non-null  object
 4   nppes_credentials             23827 non-null  object
 5   nppes_provider_gender         25050 non-null  object
 6   nppes_entity_code             25050 non-null  object
 7   nppes_provider_street1        25050 non-null  object
 8   nppes_provider_street2        9790 non-null   object
 9   nppes_provider_city           25050 non-null  object
 10  nppes_provider_zip5           25050 non-null  object
 11  nppes_provider_zip4           21568 non-null  object
 12  nppes_provider_state          25050 non-null  object
 13  nppes_provider_country        25050 non-null  object
 14  specialty_description         25050 non-null  object
 15  description_flag              25050 non-null  object
 16  medicare_prvdr_enroll_status  25050 non-null  object
dtypes: object(17)
memory usage: 3.2+ MB

In [8]:
prescriber.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,nppes_provider_zip5,nppes_provider_zip4,nppes_provider_state,nppes_provider_country,specialty_description,description_flag,medicare_prvdr_enroll_status
0,1003000282,BLAKEMORE,ROSIE,K,FNP,F,I,TENNESSEE PRISON FOR WOMEN,3881 STEWARTS LANE,NASHVILLE,37243,0001,TN,US,Nurse Practitioner,S,N
1,1003012022,CUDZILO,COREY,None,M.D.,M,I,2240 SUTHERLAND AVE,SUITE 103,KNOXVILLE,37919,2333,TN,US,Pulmonary Disease,S,E
2,1003013160,GRABENSTEIN,WILLIAM,P,M.D.,M,I,1822 MEMORIAL DR,None,CLARKSVILLE,37043,4605,TN,US,Family Practice,S,E
3,1003013947,OTTO,ROBERT,J,M.D.,M,I,2400 PATTERSON STREET SUITE 100,None,NASHVILLE,37203,2786,TN,US,Orthopedic Surgery,S,E
4,1003017963,TODD,JOSHUA,W,M.D.,M,I,1819 W CLINCH AVE,SUITE 108,KNOXVILLE,37916,2435,TN,US,Cardiology,S,E

In [9]:
query1 = """

SELECT 
    * 
FROM 
    prescription

"""

with engine.connect() as connection:
    result = connection.execute(text(query1))
    prescription = pd.DataFrame(result.fetchall(), columns=result.keys())

prescription.head()

,npi,drug_name,bene_count,total_claim_count,total_30_day_fill_count,total_day_supply,total_drug_cost,bene_count_ge65,bene_count_ge65_suppress_flag,total_claim_count_ge65,ge65_suppress_flag,total_30_day_fill_count_ge65,total_day_supply_ge65,total_drug_cost_ge65
0,1427075894,RALOXIFENE HCL,None,18,28.0,840,1009.66,None,*,18.0,None,28.0,840.0,1009.66
1,1003858150,GLIMEPIRIDE,None,12,16.0,480,270.86,None,*,None,*,None,None,None
2,1184627192,TAMSULOSIN HCL,None,14,24.0,698,353.62,None,#,None,#,None,None,None
3,1306111497,SPIRIVA,None,13,13.0,390,4783.28,None,*,None,*,None,None,None
4,1285658237,SPIRIVA,None,13,13.0,390,4855.95,None,#,None,#,None,None,None

In [27]:
query3 = """

SELECT pn.drug_name,fc.state, fc.county, pn.total_claim_count, p.population FROM prescriber AS pr
JOIN prescription AS pn
ON pr.npi = pn.npi
JOIN zip_fips AS zp
ON zp.zip = pr.nppes_provider_zip5
JOIN population AS p
ON p.fipscounty = zp.fipscounty
JOIN fips_county AS fc
ON fc.fipscounty = p.fipscounty
JOIN drug AS d
ON d.drug_name = pn.drug_name
WHERE fc.state =  'TN' AND d.opioid_drug_flag = 'Y'

"""

with engine.connect() as connection:
    result = connection.execute(text(query3))
    opoid_county = pd.DataFrame(result.fetchall(), columns=result.keys())
    
opoid_county

,drug_name,state,county,total_claim_count,population
0,OXYCODONE-ACETAMINOPHEN,TN,BRADLEY,525,103666
1,OXYCODONE-ACETAMINOPHEN,TN,HAMILTON,525,354589
2,HYDROCODONE-ACETAMINOPHEN,TN,HAMILTON,79,354589
3,HYDROCODONE-ACETAMINOPHEN,TN,DAVIDSON,12,678322
4,TRAMADOL HCL,TN,CUMBERLAND,26,58178
...,...,...,...,...,...
52584,MORPHINE SULFATE ER,TN,KNOX,19,452286
52585,MORPHINE SULFATE ER,TN,SEVIER,19,95523
52586,OXYCONTIN,TN,RHEA,20,32478
52587,OXYCONTIN,TN,MEIGS,20,11830
52588,OXYCONTIN,TN,BLEDSOE,20,14413

In [30]:
# Convert total_claim_count and population to numeric
opoid_county['total_claim_count'] = opoid_county['total_claim_count'].astype(float)
opoid_county['population'] = opoid_county['population'].astype(float)
opoid_county.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52589 entries, 0 to 52588
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   drug_name          52589 non-null  object
 1   state              52589 non-null  object
 2   county             52589 non-null  object
 3   total_claim_count  52589 non-null  float64
 4   population         52589 non-null  float64
dtypes: float64(2), object(3)
memory usage: 2.0+ MB

In [57]:
county_summary_df = (opoid_county.groupby('county')[['total_claim_count', 'population']].sum().reset_index())
county_summary_df

        county  total_claim_count   population
0     ANDERSON            52701.0   55671506.0
1      BEDFORD            41506.0   24082956.0
2       BENTON            12046.0    1502322.0
3      BLEDSOE            22145.0    3502359.0
4       BLOUNT            62747.0  146840925.0
..         ...                ...          ...
90       WAYNE            22481.0    3994407.0
91     WEAKLEY            67839.0   20299376.0
92       WHITE             9829.0    3668766.0
93  WILLIAMSON           104875.0  313998280.0
94      WILSON            65860.0  106707672.0

[95 rows x 3 columns]

In [32]:
county_summary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   county             95 non-null     object
 1   total_claim_count  95 non-null     float64
 2   population         95 non-null     float64
dtypes: float64(2), object(1)
memory usage: 2.4+ KB

In [58]:
# findind claim count per 1000 people for each county and rount to 2 decimals
county_summary_df['claim_per_1000'] = (county_summary_df['total_claim_count']/county_summary_df['population']* 1000)
county_summary_df['claim_per_1000'] = county_summary_df['claim_per_1000'] .round(2)

In [59]:
# sorted counties by claim_per_1000 in descending order to see the highest prescription at the top 
county_summary_sorted = county_summary_df.sort_values(by ='claim_per_1000', ascending =False)
county_summary_sorted

        county  total_claim_count    population  claim_per_1000
68     PICKETT            12914.0  4.513190e+05           28.61
33     HANCOCK            15952.0  9.313050e+05           17.13
87   VAN BUREN            23578.0  1.623050e+06           14.53
13        CLAY             6920.0  4.840920e+05           14.29
63       MOORE            44689.0  3.327456e+06           13.43
..         ...                ...           ...             ...
32    HAMILTON           229988.0  9.552628e+08            0.24
74  RUTHERFORD            83305.0  3.614302e+08            0.23
46        KNOX           280484.0  1.707832e+09            0.16
18    DAVIDSON           320821.0  3.222030e+09            0.10
78      SHELBY           240211.0  3.419390e+09            0.07

[95 rows x 4 columns]

In [60]:
# 10% of total no of counties
no_of_counties = 95
ten_percent = no_of_counties * 0.10
value = round(ten_percent)
value

10

In [61]:
# selected top 10 rows from the sorted list
top_10 = county_summary_sorted[:10]
top_10

       county  total_claim_count  population  claim_per_1000
68    PICKETT            12914.0    451319.0           28.61
33    HANCOCK            15952.0    931305.0           17.13
87  VAN BUREN            23578.0   1623050.0           14.53
13       CLAY             6920.0    484092.0           14.29
63      MOORE            44689.0   3327456.0           13.43
67      PERRY             6681.0    543858.0           12.28
84  TROUSDALE            29060.0   2833679.0           10.26
75      SCOTT            26159.0   3050911.0            8.57
2      BENTON            12046.0   1502322.0            8.02
24   FENTRESS            15586.0   1973400.0            7.90

In [62]:
# Resetting the index of the top 10 counties from 1 to 10.
top10_summary_df =top_10.reset_index(drop=True)
top10_summary_df.index = top10_summary_df.index+1
top10_summary_df

       county  total_claim_count  population  claim_per_1000
1     PICKETT            12914.0    451319.0           28.61
2     HANCOCK            15952.0    931305.0           17.13
3   VAN BUREN            23578.0   1623050.0           14.53
4        CLAY             6920.0    484092.0           14.29
5       MOORE            44689.0   3327456.0           13.43
6       PERRY             6681.0    543858.0           12.28
7   TROUSDALE            29060.0   2833679.0           10.26
8       SCOTT            26159.0   3050911.0            8.57
9      BENTON            12046.0   1502322.0            8.02
10   FENTRESS            15586.0   1973400.0            7.90